### ISSUE TITLE
What happened to createTypeboxDto?

### ISSUE THREAD

**Issue by mkadirtan** [jayalfredprufrock/nestjs-typebox#38]
You mention in the README, you want to continue with decorator-based approach, can you give an example usage?

**Comment by jayalfredprufrock** [comment]
My apologies, I've been meaning to update the README with new examples. Usage is actually simpler now. I'll get the README updated today. Hope you find this new approach preferable as I do.

**Comment by jayalfredprufrock** [comment]
README has been updated. I might follow up later with a more formalized section detailing the different options and defaults, but wanted to start with annotated examples because I generally find them easier to consume.

I don't suspect there will be any more breaking changes, but I want to test drive the library a little longer in some of my projects before I bump up to v3.x and consider things stable.  Definitely welcome any thoughts/ideas you might have about the library

-Andrew

**Comment by mkadirtan** [comment]
Appreciate the quick response & solution 🙏
