### ISSUE TITLE
❓ 3.0 Release Requirements

### ISSUE THREAD

**Issue by JoeHillyard** [jayalfredprufrock/nestjs-typebox#57]
I am looking to migrate multiple Nest projects to drizzle and this library would be a huge help!

I can see that 3.0 is in pre-release, what are the requirements for the final release? Any good first issues I can help with?

Thanks!

**Comment by jayalfredprufrock** [comment]
Hi there, the main reason I have been holding off on v3 is I have been hoping somebody would package a generic typebox-based validation library that could do most of the heavy lifting for validating and transforming request/response payloads so this library could focus mainly on nest integration, decorators, openapi support, etc. There has been quite a lot of movement in typebox around transformers, error handling when using complex union types, cleaning/default values, etc., but typebox is meant to be fairly low-level and requires registering custom formatters for even standard things like validating emails. (though the maintainer has example implementations for many popular formats). An opinionated layer on top that smooths out some of the complexities is what I'm hoping to find/build.

Otherwise, I consider v3 stable and use it in several production APIs. I'll likely do another review of existing libraries soon and hopefully find a suitable library to integrate with. I don't mind writing it myself, but it would probably be better as a separate library so the wider typebox community could benefit. Just as soon as I have a longer-term plan in place I'll lift the pre-release flag and announce a public roadmap for the future. In the meantime, please send any issues/ideas my way to improve this library, as I do have every intention to keep supporting it while I use NestJs as my daily driver framework.

**Comment by JoeHillyard** [comment]
Could [this library](https://github.com/jtlapp/typebox-validators) do some of that heavy lifting?
